[package]
name = "bme_680"
version = "0.1.0"
authors = ["starfish-bee <77985573+starfish-bee@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2c = { path = "../i2c" }
